# define all the global constants in this file
POP_MARGIN = 20
POP_SPREAD = 10

MEAN_ENERGY = 100
STDDEV_ENERGY = 10

RESERVE_SIZE = 20
MEAN_RESERVE = 50
STDDEV_RESERVE = 20
DECAY_RATE = 1

EXPLORER_MEAN_STAMINA = 1.5
EXPLORER_STD_STAMINA = 0.5

EXPLOITER_MEAN_STAMINA = 2.5
EXPLOITER_STD_STAMINA = 1.0

EXPLORER_SENSE_RANGE = 10
EXPLORER_COMM_RANGE = 20

EXPLOITER_COMM_RANGE = 5
EXPLOITER_SENSE_RANGE = 10

SENSE_STEPS = 5
COMMUNICATION_STEPS = 10
COMMUNICATION_PROB = 0.3

EXPLORER_MINING_RATE = 0.5
EXPLOITER_MINING_RATE = 1

EXPLORER_RATIO = 0.1
