# define all the global constants in this file

MEAN_ENERGY = 100
STDDEV_ENERGY = 10

EXPLORER_MEAN_STAMINA = 1.5
EXPLORER_STD_STAMINA = 0.5

EXPLOITER_MEAN_STAMINA = 2.5
EXPLOITER_STD_STAMINA = 1.0

EXPLORER_SENSE_RANGE = 10
EXPLORER_COMM_RANGE = 20

EXPLOITER_COMM_RANGE = 5
EXPLOITER_SENSE_RANGE = 10

EXPLORER_RATIO = 0.1
